name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    name: Ruby ${{ matrix.ruby }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        ruby: [ "3.3" ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install Firebird client
        run: |
          sudo apt-get update
          sudo apt-get install -y  build-essential firebird-dev libfbclient2 firebird3.0-utils

      - name: Start Firebird container in background
        run: |
          docker run -d \
            --name firebird \
            -e ISC_PASSWORD=masterkey \
            -e FIREBIRD_USER=SYSDBA \
            -e FIREBIRD_PASSWORD=masterkey \
            -e FIREBIRD_DATABASE=test.fdb \
            -e FIREBIRD_DATABASE_DEFAULT_CHARSET=UTF8 \
            -p 3050:3050 \
            firebirdsql/firebird:5

      - name: Wait for Firebird to be ready
        run: |
          echo "Waiting for Firebird..."
          for i in {1..30}; do
            if echo "SELECT 1 FROM RDB\$DATABASE;" | isql-fb -user SYSDBA -password masterkey localhost:3050/test.fdb; then
              echo "Firebird is ready!"
              break
            fi
            sleep 2
          done
          
      - name: Compile native extension
        run: bundle exec rake compile
    
      - name: Run tests
        run: bundle exec rake test
        env:
          FB_TEST_DATABASE: "localhost:3050/test.fdb"
          FB_TEST_USER: "SYSDBA"
          FB_TEST_PASSWORD: "masterkey"
