name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    name: Ruby ${{ matrix.ruby }} Rails ${{ matrix.rails }} on ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        ruby:
          - "3.1.4"

        rails:
          # - "5.latest"
          # - "6.latest"
          - "7.latest"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: juarezr/firebirdsql-github-action@v1.2.0
        with:
          version: "v3"
          firebird_database: "my_database.fdb"
          firebird_user: "SYSDBA"
          firebird_password: "masterkey"

      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install dependencies
        run: |
            sudo apt-get update -y
            sudo apt-get install firebird-dev nodejs -y
      - name: Compile and run tests
        run: |
          bundle exec rake compile:fb_ext test
