name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    name: Ruby ${{ matrix.ruby }} Rails ${{ matrix.rails }} on ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        ruby:
          - "3.1.4"

        rails:
          - "5.latest"
          - "6.latest"
          - "7.latest"

    runs-on: ${{ matrix.os }}

    steps:
      # - uses: juarezr/firebirdsql-github-action@v1.2.0
      #   with:
      #     version: "v3"
      #     firebird_database: "my_database.fdb"
      #     firebird_user: "sysdba"
      #     firebird_password: "masterkey"

      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install dependencies
        run: |
            sudo apt-get update -qq
            sudo DEBIAN_FRONTEND=noninteractive apt-get install -qq build-essential patch ruby-dev zlib1g-dev liblzma-dev firebird-dev firebird2.5-superclassic
            bundle install

      - name: Prepare Firebird
        run: |
            sudo gsec -modify SYSDBA -pw masterkey
            sudo mkdir -p /tmp/firebird
            sudo chown firebird.firebird /tmp/firebird
            sudo chmod 0777 /tmp/firebird

      - name: Compile and run tests
        run: |
          bundle install
          bundle exec rake compile:fb_ext  install test
