name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      firebird:
        image: firebirdsql/firebird:5.0.0
        env:
          ISC_PASSWORD: masterkey
          FIREBIRD_DATABASE: test.fdb
          FIREBIRD_USER: SYSDBA
          FIREBIRD_PASSWORD: masterkey
        options: >-
          --health-cmd "bash -c 'echo \"SELECT 1 FROM RDB\\\$DATABASE;\" | isql-fb -user SYSDBA -password masterkey localhost:test.fdb'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.6'
          bundler-cache: true

      - name: Install Firebird client
        run: |
          sudo apt-get update
          sudo apt-get install -y libfbclient2

      - name: Compile extension
        run: bundle exec rake compile

      - name: Run tests
        run: bundle exec rake test
        env:
          FB_TEST_DATABASE: "localhost:test.fdb"
          FB_TEST_USER: "SYSDBA"
          FB_TEST_PASSWORD: "masterkey"
