name: Ruby
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Ruby ${{ matrix.ruby }} Rails ${{ matrix.rails }} on ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        ruby:
          - "3.3.6"
        rails:
          # - "5.latest"
          # - "6.latest"
          - "7.latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git-core zlib1g-dev build-essential libssl-dev \
            libreadline-dev libyaml-dev libxml2-dev libxslt1-dev libcurl4-openssl-dev \
            software-properties-common libffi-dev firebird3.0-server firebird-dev libfbclient2
      
      - name: Configure Firebird
        run: |
          sudo sed -i 's/#WireCrypt = Enabled/WireCrypt = Enabled/' /etc/firebird/3.0/firebird.conf
          sudo sed -i 's/RemoteBindAddress = localhost/RemoteBindAddress = 0.0.0.0/' /etc/firebird/3.0/firebird.conf
          sudo sed -i 's/#AuthServer = Srp256, Srp, Win_Sspi, Legacy_Auth/AuthServer = Legacy_Auth, Srp256, Srp/' /etc/firebird/3.0/firebird.conf
          sudo sed -i 's/#AuthClient = Srp256, Srp, Win_Sspi, Legacy_Auth/AuthClient = Legacy_Auth, Srp256, Srp/' /etc/firebird/3.0/firebird.conf
          sudo sed -i 's/#UserManager = Srp/UserManager = Legacy_UserManager, Srp/' /etc/firebird/3.0/firebird.conf
          echo "SYSDBA:masterkey" | sudo tee /etc/firebird/3.0/SYSDBA.password
          sudo chown firebird:firebird /etc/firebird/3.0/SYSDBA.password
          sudo chmod 600 /etc/firebird/3.0/SYSDBA.password
          sudo systemctl restart firebird3.0
          sleep 5
      
      - name: Create test database
        run: |
          cat > /tmp/create_db.sql << EOF
CREATE DATABASE 'localhost:/tmp/test.fdb' 
USER 'SYSDBA' PASSWORD 'masterkey' 
PAGE_SIZE 8192 DEFAULT CHARACTER SET UTF8;
QUIT;
EOF
          isql-fb -i /tmp/create_db.sql
          sudo chmod 666 /tmp/test.fdb
      
      - name: Verify Firebird is running
        run: |
          ps aux | grep firebird
          echo "SELECT 1 FROM RDB\$DATABASE;" | isql-fb localhost:/tmp/test.fdb -u SYSDBA -p masterkey
      
      - name: Compile and install gem
        run: bundle exec rake install 
      
      - name: Compile extension
        run: bundle exec rake compile
      
      - name: Run tests
        run: bundle exec rake test
        env:
          FB_TEST_DATABASE: "localhost:/tmp/test.fdb"
          FB_TEST_USER: "SYSDBA"
          FB_TEST_PASSWORD: "masterkey"
