name: Ruby

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build:
    name: Ruby ${{ matrix.ruby }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        ruby: [ "3.3" ]

    services:
      firebird:
        image: firebirdsql/firebird.latest
        env:
          FIREBIRD_ROOT_PASSWORD: masterkey
          FIREBIRD_USER: SYSDBA
          FIREBIRD_PASSWORD: masterkey
          FIREBIRD_DATABASE: test.fdb
          FIREBIRD_DATABASE_DEFAULT_CHARSET: UTF8          
        ports:
          - 3050:3050
        options: >-
          --health-cmd "bash -c 'echo \"SELECT 1 FROM RDB\\\$DATABASE;\" | /usr/bin/isql-fb -user SYSDBA -password masterkey localhost:employee'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install Firebird client and dev libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y firebird-dev libfbclient2 firebird3.0-utils

      - name: Wait for Firebird to be ready
        run: |
          echo "Waiting for Firebird service..."
          for i in {1..30}; do
            if echo "SELECT 1 FROM RDB\$DATABASE;" | isql-fb -user SYSDBA -password masterkey firebird:3050/employee; then
              echo "Firebird is ready!"
              break
            fi
            sleep 2
          done

      - name: Create test database
        run: |
          echo "CREATE DATABASE 'firebird:3050:test.fdb' USER 'SYSDBA' PASSWORD 'masterkey' PAGE_SIZE 8192;" | isql-fb

      - name: Run tests
        run: bundle exec rake test
        env:
          FB_TEST_DATABASE: "firebird:3050:test.fdb"
          FB_TEST_USER: "SYSDBA"
          FB_TEST_PASSWORD: "masterkey"
