name: Ruby
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Ruby ${{ matrix.ruby }} Rails ${{ matrix.rails }} on ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        ruby:
          - "3.3.6"
        rails:
          # - "5.latest"
          # - "6.latest"
          - "7.latest"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git-core zlib1g-dev build-essential libssl-dev \
            libreadline-dev libyaml-dev libxml2-dev libxslt1-dev libcurl4-openssl-dev \
            software-properties-common libffi-dev firebird3.0-server firebird-dev libfbclient2
      
      - name: Configure Firebird and create database
        run: |
          # Configurar Firebird
          sudo sed -i 's/RemoteBindAddress = localhost/# RemoteBindAddress = localhost/' /etc/firebird/3.0/firebird.conf
          sudo systemctl restart firebird3.0
          sleep 5
          # Crear base de datos como usuario firebird
          sudo -u firebird /usr/lib/x86_64-linux-gnu/firebird/3.0/bin/isql-fb -user SYSDBA -password masterkey << 'EOF' || true
                            CREATE DATABASE '/tmp/test.fdb';
                            QUIT;
                          EOF
          # Dar permisos
          sudo chmod 666 /tmp/test.fdb
          ls -la /tmp/test.fdb
      
      - name: Verify Firebird is running
        run: |
          ps aux | grep firebird
          echo "SELECT 1 FROM RDB\$DATABASE;" | isql-fb localhost:/tmp/test.fdb -u SYSDBA -p masterkey
      
      - name: Compile and install gem
        run: bundle exec rake install 
      
      - name: Compile extension
        run: bundle exec rake compile
      
      - name: Run tests
        run: bundle exec rake test
        env:
          FB_TEST_DATABASE: "/tmp/test.fdb"
          FB_TEST_USER: "SYSDBA"
          FB_TEST_PASSWORD: "masterkey"
