name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    name: Ruby ${{ matrix.ruby }} Rails ${{ matrix.rails }} on ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
        ruby:
          - "3.3.6"

        rails:   
          - "7.latest"

    runs-on: ${{ matrix.os }}
    
    services:
      firebird:
        image: jacobalberty/firebird:5.0
        ports:
          - 3050:3050
        env:
          ISC_PASSWORD: masterkey

    steps:   
      - uses: actions/checkout@v3
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install dependencies
        run: |
            sudo apt-get update -y
            sudo apt-get install git-core zlib1g-dev build-essential libssl-dev libreadline-dev libyaml-dev libxml2-dev libxslt1-dev libcurl4-openssl-dev software-properties-common libffi-dev libfbclient2 firebird-dev -y
      - name: Compile and run tests
        run: |
          bundle exec rake install
          bundle exec rake test
          env:
            FB_TEST_DATABASE: "localhost:/firebird/data/test.fdb"
