name: Ruby
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    name: Ruby ${{ matrix.ruby }} Rails ${{ matrix.rails }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    
    services:
      firebird:
        image: jacobalberty/firebird:v3.0
        env:
          FIREBIRD_DATABASE: test.fdb
          FIREBIRD_USER: SYSDBA
          FIREBIRD_PASSWORD: masterkey
          ISC_PASSWORD: masterkey
        ports:
          - 3050:3050
        options: >-
          --health-cmd "echo 'SELECT 1 FROM RDB\$DATABASE;' | isql-fb -user SYSDBA -password masterkey localhost:test.fdb || exit 0"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    strategy:
      matrix:
        os:
          - ubuntu-latest
        ruby:
          - "3.3.6"
        rails:
          # - "5.latest"
          # - "6.latest"
          - "7.latest"
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      
      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y git-core zlib1g-dev build-essential libssl-dev \
            libreadline-dev libyaml-dev libxml2-dev libxslt1-dev libcurl4-openssl-dev \
            software-properties-common libffi-dev firebird-dev libfbclient2
      
      - name: Wait for Firebird to be ready
        run: |
          echo "Waiting for Firebird to be ready..."
          for i in {1..30}; do
            if nc -z localhost 3050; then
              echo "Firebird is ready!"
              sleep 5
              break
            fi
            echo "Waiting... ($i/30)"
            sleep 2
          done
      
      - name: Verify Firebird connection
        run: |
          sudo apt-get install -y firebird3.0-utils
          echo "SELECT 1 FROM RDB\$DATABASE;" | isql-fb -user SYSDBA -password masterkey localhost:test.fdb || echo "Database may not exist yet, will be created by tests"
      
      - name: Compile and install gem
        run: bundle exec rake install 
      
      - name: Compile extension
        run: bundle exec rake compile
      
      - name: Run tests
        run: bundle exec rake test
        env:
          FB_TEST_DATABASE: "localhost:test.fdb"
          FB_TEST_USER: "SYSDBA"
          FB_TEST_PASSWORD: "masterkey"
