name: Build fb gem

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.2']
        # ruby-version: ['2.6', '2.7', '3.0', '3.1', '3.2']
    steps:
    - uses: actions/checkout@v3
    - uses: juarezr/firebirdsql-github-action@v1.2.0
      with:
        version: 'v3.0'
        firebird_database: 'my_database.fdb'
        firebird_user: 'sysdba'
        firebird_password: 'masterkey'
    - name: Set up Ruby
    # To automatically get bug fixes and new Ruby versions for ruby/setup-ruby,
    # change this to (see https://github.com/ruby/setup-ruby#versioning):
    # uses: ruby/setup-ruby@v1
      uses: ruby/setup-ruby@55283cc23133118229fd3f97f9336ee23a179fcf # v1.146.0
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y libfbclient2 firebird-dev 
        gem install bundler
        bundle install
    - name: Run Tests
      run: bundle exec rake compile:fb_ext test
